[mgr]
prepend_keymap = [

  # Compression
  { on = [ "c", "a" ], run = "plugin compress", desc = "Archive selected files"},

  # Custom gotos
  { on = [ "g", "e" ], run = "cd ~/Documents/Uni/Estructuras", desc = "Goto /Estructuras"},
  { on = [ "g", "u" ], run = "cd ~/Documents/Uni", desc = "Goto /Uni"},
  { on = [ "g", "d" ], run = "cd ~/Documents", desc = "Goto /Documents"},

  # Open shell
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open $SHELL here", for = "unix"},

  # Toggle preview pane
  { on = "t", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane"},
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane"},

  # Open files and enter directories all with 'l'
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file"},
  { on = "L", run = "open --interactive", desc = "Open the file interactively"},

  # Chmod selected files
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files"},

  # Calculate size of selected or cwd
  { on = "~", run = "plugin what-size -- '-c'", desc = "Calc size of selection or cwd" },

  # Restore trashed files
  { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
  
  # Navigate up and down without wraparound scrolling
  # { on = "k", run = "arrow -1", desc = "Previous file" },
  # { on = "j", run = "arrow 1", desc = "Next file" },

  # Preferences-by-location 
  
  # Toggle Hidden
  # { on = ".", run = [ "hidden toggle", "plugin pref-by-location -- save" ], desc = "Toggle the visibility of hidden files" },

  # Linemode
  # { on = [ "m", "s" ], run = [ "linemode size", "plugin pref-by-location -- save" ],        desc = "Linemode: size" },
  # { on = [ "m", "p" ], run = [ "linemode permissions", "plugin pref-by-location -- save" ], desc = "Linemode: permissions" },
  # { on = [ "m", "b" ], run = [ "linemode btime", "plugin pref-by-location -- save" ],       desc = "Linemode: btime" },
  # { on = [ "m", "m" ], run = [ "linemode mtime", "plugin pref-by-location -- save" ],       desc = "Linemode: mtime" },
  # { on = [ "m", "o" ], run = [ "linemode owner", "plugin pref-by-location -- save" ],       desc = "Linemode: owner" },
  # { on = [ "m", "n" ], run = [ "linemode none", "plugin pref-by-location -- save" ],        desc = "Linemode: none" },
  # Custom size_and_mtime linemode
  # { on = [ "u", "S" ], run = [ "linemode size_and_mtime", "plugin pref-by-location -- save" ], desc = "Show Size and Modified time" },

  # Sorting
  # Any changes during disabled state won't be saved to save file.
  # { on = [ ",", "t" ], run = "plugin pref-by-location -- toggle",                                                desc = "Toggle auto-save preferences" },
  # { on = [ ",", "d" ], run = "plugin pref-by-location -- disable",                                               desc = "Disable auto-save preferences" },
  # This will reset any preference changes for the current working directory (CWD),
  # then fall back to the predefined preferences in init.lua or yazi.toml.
  # { on = [ ",", "R" ], run = [ "plugin pref-by-location -- reset" ],                                             desc = "Reset preference of cwd" },
  # { on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime", "plugin pref-by-location -- save" ], desc = "Sort by modified time" },
  # { on = [ ",", "M" ], run = [ "sort mtime --reverse", "linemode mtime", "plugin pref-by-location -- save" ],    desc = "Sort by modified time (reverse)" },
  # { on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime", "plugin pref-by-location -- save" ], desc = "Sort by birth time" },
  # { on = [ ",", "B" ], run = [ "sort btime --reverse", "linemode btime", "plugin pref-by-location -- save" ],    desc = "Sort by birth time (reverse)" },
  # { on = [ ",", "e" ], run = [ "sort extension --reverse=no", "plugin pref-by-location -- save" ],               desc = "Sort by extension" },
  # { on = [ ",", "E" ], run = [ "sort extension --reverse", "plugin pref-by-location -- save" ],                  desc = "Sort by extension (reverse)" },
  # { on = [ ",", "a" ], run = [ "sort alphabetical --reverse=no", "plugin pref-by-location -- save" ],            desc = "Sort alphabetically" },
  # { on = [ ",", "A" ], run = [ "sort alphabetical --reverse", "plugin pref-by-location -- save" ],               desc = "Sort alphabetically (reverse)" },
  # { on = [ ",", "n" ], run = [ "sort natural --reverse=no", "plugin pref-by-location -- save" ],                 desc = "Sort naturally" },
  # { on = [ ",", "N" ], run = [ "sort natural --reverse", "plugin pref-by-location -- save" ],                    desc = "Sort naturally (reverse)" },
  # --sensitive=no or --sensitive
  # { on = [ ",", "N" ], run = [ "sort natural --reverse=no --sensitive", "plugin pref-by-location -- save" ],                    desc = "Sort naturally" },
  # { on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size", "plugin pref-by-location -- save" ],   desc = "Sort by size" },
  # { on = [ ",", "S" ], run = [ "sort size --reverse", "linemode size", "plugin pref-by-location -- save" ],      desc = "Sort by size (reverse)" },
  # { on = [ ",", "r" ], run = [ "sort random --reverse=no", "plugin pref-by-location -- save" ],                  desc = "Sort randomly" },
]
