[manager]
linemode = "size"

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '${EDITOR:=nvim} "$@"', desc = "nvim", block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "xdg-open default" },
]
