[mgr]
linemode = "size"

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '${EDITOR:=nvim} "$@"', desc = "nvim", block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "xdg-open default" },
]

[open]
prepend_rules = [
  { name = "*.html", use = [ "open", "edit" ] },
]

[input]
#create
create_title  = [ "Create:", "Create (dir):" ]
create_origin = "hovered"
create_offset = [ 0, 1, 50, 3 ]

[plugin]
prepend_fetchers = [
  { id = "git", name = "*", run = "git"},
  { id = "git", name = "*/", run = "git"},
]
